version: '3.1'
services:
  perfomans-db:
    image: postgres:14-alpine
    container_name: perfomans-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=perfomans
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root